apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-demo
spec:
  version: 8.11.1
  count: 1
  elasticsearchRef:
    name: elasticsearch-demo
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 512Mi
            cpu: 0.2
          limits:
            memory: 1Gi
            cpu: 0.5