apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elasticsearch-tls-production
  namespace: elastic
spec:
  secretName: elasticsearch-tls
  dnsNames:
    - elastic.wgbh-mla.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
