apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana-tls
  namespace: elastic
spec:
  secretName: kibana-tls
  dnsNames:
    - search.wgbh-mla.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
