apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/WGBH-MLA/cluster-deploy-dev.git
    targetRevision: main  # Change this if using a different branch
    path: argo-cd-apps/eck-operator  # Adjust based on where values.yaml is stored
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: "managedNamespaces"
          value: "{elastic-system}"
        - name: "createClusterScopedResources"
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true